import kfp
from kfp import dsl
from kfp.components import func_to_container_op
import json
from xgboost import XGBRegressor
from sklearn.metrics import accuracy_score


@func_to_container_op
def show_results(linear_regression, random_forest, g_boost) -> None:

    print(f"linear regression: {linear_regression}")
    print(f"random forest: {random_forest}")
    print(f"gredient boost: {g_boost}")




@dsl.pipeline(name='Car price Pipeline', description='')
def car_price_pipeline():

    # Loads the yaml manifest for each component
    load = kfp.components.load_component_from_file('load_data/load_data.yaml')
    create_features = kfp.components.load_component_from_file('create_features/create_features.yaml')
    linear_regression = kfp.components.load_component_from_file('linear_regression/linear_regression.yaml')
    random_forest = kfp.components.load_component_from_file('random_forest/random_forest.yaml')
    g_boost = kfp.components.load_component_from_file('g_boost/g_boost.yaml')

    # Run load_data task
    load_task = load()

    # Run tasks "decison_tree" and "logistic_regression" given
    # the output generated by "load_task".
    create_features_task = create_features(load_task.output)
    linear_regression_task = linear_regression(create_features_task.output)
    random_forest_task = random_forest(create_features_task.output)
    g_boost_task = g_boost(create_features_task.output)
    # Given the outputs from "decision_tree" and "logistic_regression"
    # the component "show_results" is called to print the results.
    show_results(linear_regression_task.output, random_forest_task, g_boost_task)


if __name__ == '__main__':
    kfp.compiler.Compiler().compile(car_price_pipeline, 'car_price_pipeline.yaml')