name: Train for model Function
description: Train the model with the best parameter found


inputs:
- {name: Processed_Data, type: LocalPath, description: 'Path where processed_data is stored.'}
- {name: Best_Parameters, type: LocalPath, description: 'Path where best parameter are stored.'}
outputs:
- {name: Results, type: LocalPath, description: 'Path where dump of model will be saved.'}

implementation:
  container:
    image: ossalag00/trainv1
    command: [
      python, train.py,

      --processed_data,
      {inputPath: Processed_Data},

      --best_parameters,
      {inputhPath: Best_Parameters},

      --results,
      {outputPath: Results},

    ]